### PR TITLE
docs: copy over new somatic VCF section

### PR DESCRIPTION
**Pull request by a-frantz**
Needs formatting updates before being pulled in, but this is the up-to-date content.

### CODE REVIEW

**Review by claymcleod — APPROVED** [review]

**Comment by claymcleod** [comment]
You ready for this to be merged in?

**Comment by a-frantz** [comment]
No not yet. Some of the special formatting from the old repo didn't carry over and I haven't restyled that yet.

Also, it seems with numbered lists in the new repo there's newline padding around any element with a nested unordered list, and no newlines between other elements. It looks odd to me, and I don't see why it's doing that. Something to do with the theme/template I'd guess. Would @bgcurran be the one to ask about that?

**Comment by a-frantz** [comment]
This is ready to go, but I'm not a fan of the whitespace in the "Somatic VCF pipeline steps" list. I think that's being controlled site-wide, so not going to mess with it myself.

**Comment by claymcleod** [comment]
@a-frantz that should fix it ^

**Pull request merged**
